version: 2
project_name: connect-runtime-wombat

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

git:
  prerelease_suffix: "-"

before:
  hooks:
    - go mod tidy

builds:
  - id: connect-runtime-wombat
    main: ./
    binary: connect-runtime-wombat
    ldflags:
      - -w -s
      - -X main.Version={{.Version}}
      - -X main.CommitHash={{.ShortCommit}}
      - -X main.BuildTimestamp={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: connect-runtime-wombat
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

dockers:
  - id: ecr-amd64
    ids:
      - connect-runtime-wombat
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Tag }}-amd64"
      - "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Version }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - id: ecr-arm64
    ids:
      - connect-runtime-wombat
    goos: linux
    goarch: arm64
    image_templates:
      - "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Tag }}-arm64"
      - "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Version }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Tag }}"
    image_templates:
      - "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Tag }}-amd64"
      - "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Tag }}-arm64"

  - name_template: "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Version }}"
    image_templates:
      - "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Version }}-amd64"
      - "{{ .Env.AWS_ECR_ADDR }}/connect-runtime-wombat:{{ .Version }}-arm64"

sboms:
  - id: "connect-runtime-wombat"
    artifacts: binary

release:
  make_latest: false
  prerelease: auto

changelog:
  use: github
  sort: asc
  groups:
    - title: 'Changes:'
      order: 999
  filters:
    exclude:
      - '^Merge pull request'
      - '^Merge branch'