version: "3"
tasks:
  build:
    desc: Build the wombat runtime
    cmds:
      - go mod tidy
      - go build -tags "{{.TAGS}}" -o ../../target/runtime-wombat *.go

  run:
    desc: Run the vent with the provided APP_ID
    dotenv:
      - "{{.HOME}}/.synadia/vent.env"
    requires:
      vars:
        - APP_ID
    cmds:
      - go mod tidy
      - go run ./*.go {{.APP_ID}}
