# .github/workflows/release.yaml

name: Edge

on:
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  id-token: write

env:
  GOPRIVATE: github.com/synadia-io/*

jobs:
  docker:
    name: Build the docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DEV_AWS_ECR_ADDR }}/connect-runtime-wombat
          tags: |
            type=ref,event=branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.DEV_AWS_ECR_PUSH_ROLE }}
          aws-region: ${{ vars.DEV_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
