# .github/workflows/validate-yaml.yml

name: Validate YAML

on:
  # disabling this for the time being. It has a dependency on the component schema which we cannot satisfy at the moment.
#  pull_request:
#    paths:
#    - '.connect/*/*.yml'
#    - 'schema.json'
  workflow_dispatch:

permissions:
  contents: read
  packages: none

env:
  GOPRIVATE: github.com/synadia-io/*

jobs:
  test:
    name: Validate YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML
        run: |
          curl --silent https://raw.githubusercontent.com/synadia-io/connect/refs/heads/main/schemas/component.json -O
          npx --yes ajv-cli validate -s component.json -d ".connect/*/*.yml" --verbose
